/*
 * 
 * Generated by http://www.wordconstructor.com/index.php based on  words nicequery and mydata
 */
	
var jobNames = ['nicerayge'
                , 'nicequury'
                , 'nicatuere'
                , 'nicequesy'
                , 'nicaqeary'
                , 'nicequigo'
                , 'titequori'
                , 'nocaqeeny'
                , 'nicotuery'
                , 'noneruery'
                , 'ticequery'
                , 'cicotairy'
                , 'nicequeca'
                , 'narenuemy'
                , 'tedoquiro'
                , 'ninoquary'
                , 'notequepe'
                , 'nicequisy'
                , 'nocequere'
                , 'nacaquery'
                , 'gicequere'
                , 'sifeqiery'
                , 'nimeniery'
                , 'nocoguely'
                , 'tidequery'
                , 'nicaqeady'
                , 'niceqiery'
                , 'geceraycy'
                , 'niceniere'
                , 'titoqoely'
                , 'casate'
                , 'becata'
                , 'binite'
                , 'wydata'
                , 'modana'
                , 'medane'
                , 'tadasy'
                , 'werata'
                , 'mydinu'
                , 'gumate'
                , 'melara'
                , 'tydere'
                , 'tedota'
               ];


/**
 * @returns the string of a random position in jobNames
 */
function getJobRootName() {
	return jobNames[Math.floor(Math.random()*(jobNames.length + 1))];

}